language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx

env:
  - RUST_BACKTRACE=1

script:
  - cargo build
  - cargo test

cache:
  directories:
    - $HOME/.cargo

before_install:
  - wget https://www.openssl.org/source/openssl-1.0.2e.tar.gz
  - tar xvf openssl-1.0.2e.tar.gz
  - cd openssl-1.0.2e
  - case "$TRAVIS_OS_NAME" in osx) target=darwin64-x86_64-cc ;; linux) target=linux-x86_64-clang ;; esac
  - ./Configure "$target" -fPIC --prefix=$HOME/.local --openssldir=$HOME/.local/ssl
  - make
  - make install
  - cd ..
  - export OPENSSL_LIB_DIR=$HOME/.local/lib
  - export OPENSSL_INCLUDE_DIR=$HOME/.local/include
  - export OPENSSL_STATIC=yes

sudo: false

matrix:
  allow_failures:
    - rust: stable
    - rust: beta

before_deploy:
  - cargo build --release
  - mkdir target/deploy
  - target/release/se help || true
  - cp target/release/se target/deploy/se

deploy:
  - provider: s3
    access_key_id: AKIAJHLREGPHOV3PUZDQ
    secret_access_key:
      secure: pNMKx+qfRKWISIHHY1hQcDUdTRSr8POAg0oOcQqqehD/x0jcq4ao0A1K4sngwaRaXrqC+cBWvsjgYl9UquEJYCG4qAWR82BK/ZEjX/1a5iM90FIzzFP7FTR9bHlDlZyRpxzzNYGQSEW2+tKmu61zwZZn44LgF17dVWU6ctIdyowZNj0ernzcKUfFUg4iSwiYiHRL2mQmbjxH3iSgUkChrybq4hgTp5tnBgsatIxIECw5wn4gZhcOSOit5DwzAO+JeDjlCK0/hRQe++PbtCdFsxbGQ77eSSt2adOhjb/1w/miaDgLRJCsHfONbIcQvRWqgTtkdqW5lucLT9LZo4U2Qo5lNpIJopIyhtT+JaKPBtOsfdqJklGajldGUdjRQ0ienJqxKsu7Rd5lMoZ5LURHhG3CPifUhepH/zAri706N7y4Wpz+7c8uPE0MVx2Z6czJ0fM/gVAMDrBD5UBojhOrrw4o05U5ehu485FbRFWm35/R/RDS4hHTLOLouIaFI6hBDR4brOtK1aKjDUtZx3tICwnfCJlJzGzQDbEdrTWnpHPrmSbUmq+seS8aX/x/MLtu9lupLfmcFaGGvx2YUyImsZwAi72BbYS8gYH0bdj6d6semnVQt4HVEb14CDsqRP5tg8jyTI0cYovabmpox5V8fF0OKddPtoiIcRGcsqBbDwk=
    bucket: semantic-editor
    region: eu-central-1
    skip_cleanup: true
    local_dir: target/deploy
    upload-dir: linux
    on:
      repo: dflemstr/semantic-editor
      condition: "$TRAVIS_OS_NAME = linux && $TRAVIS_RUST_VERSION = nightly"
  - provider: s3
    access_key_id: AKIAJHLREGPHOV3PUZDQ
    secret_access_key:
      secure: pNMKx+qfRKWISIHHY1hQcDUdTRSr8POAg0oOcQqqehD/x0jcq4ao0A1K4sngwaRaXrqC+cBWvsjgYl9UquEJYCG4qAWR82BK/ZEjX/1a5iM90FIzzFP7FTR9bHlDlZyRpxzzNYGQSEW2+tKmu61zwZZn44LgF17dVWU6ctIdyowZNj0ernzcKUfFUg4iSwiYiHRL2mQmbjxH3iSgUkChrybq4hgTp5tnBgsatIxIECw5wn4gZhcOSOit5DwzAO+JeDjlCK0/hRQe++PbtCdFsxbGQ77eSSt2adOhjb/1w/miaDgLRJCsHfONbIcQvRWqgTtkdqW5lucLT9LZo4U2Qo5lNpIJopIyhtT+JaKPBtOsfdqJklGajldGUdjRQ0ienJqxKsu7Rd5lMoZ5LURHhG3CPifUhepH/zAri706N7y4Wpz+7c8uPE0MVx2Z6czJ0fM/gVAMDrBD5UBojhOrrw4o05U5ehu485FbRFWm35/R/RDS4hHTLOLouIaFI6hBDR4brOtK1aKjDUtZx3tICwnfCJlJzGzQDbEdrTWnpHPrmSbUmq+seS8aX/x/MLtu9lupLfmcFaGGvx2YUyImsZwAi72BbYS8gYH0bdj6d6semnVQt4HVEb14CDsqRP5tg8jyTI0cYovabmpox5V8fF0OKddPtoiIcRGcsqBbDwk=
    bucket: semantic-editor
    region: eu-central-1
    skip_cleanup: true
    local_dir: target/deploy
    upload-dir: osx
    on:
      repo: dflemstr/semantic-editor
      condition: "$TRAVIS_OS_NAME = osx && $TRAVIS_RUST_VERSION = nightly"
