[package]
name = "semantic-editor"
version = "0.1.0"
authors = ["David Flemström <david.flemstrom@gmail.com>"]
build = "build.rs"

[[bin]]
name = "se"

[dependencies]
clap = "1.4.0"
fern = "0.3.5"
log = "0.3.2"
rustbox = "0.7.1"
time = "0.1.32"
